cmapss:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('WAREHOUSE_HOST', 'localhost') }}"
      port: 5432
      user: warehouse
      pass: warehouse
      dbname: warehouse_db
      schema: public
      threads: 4
